config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :update, :edit]
  resources :books, only: [:new, :create, :edit, :update, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @book = current_user.books.build
      @feed_items = current_user.feed.page(params[:page]).per(5).desc
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/views/static_pages/_home_logged_in.html.slim
.py-2.w-25.mx-auto
  .card.text-center.bg-light
    .img-fluid.mt-4
      = gravatar_for current_user
    .card-body
      h4.card-title = current_user.name
      p.card-subtitle.mt-2 Number of Books: #{current_user.books.count}
      = render 'shared/status'
      .mt-2
        span.mr-4 = link_to "View my profile", user_path(current_user), class: "mx-auto btn btn-primary mr-4"
        span = link_to "Add new books", new_book_path, class: "mx-auto btn btn-info"
section.col-md-8.d-block.mx-auto
  - if @feed_items.any?
      .container
        h4.py-4.mt-2.text-center Book Feed
        ol  = render @feed_items
        = paginate @feed_items, theme: 'twitter-bootstrap-4'

app/views/static_pages/_home_not_logged_in.html.slim
section.text-center
  h1.pt-4.pb-2 Welcome to Bookshelf App!
  h3.pb-4 Let's read & put your books!
  = link_to "Sign up", signup_path, class: "btn btn-primary btn-lg mr-4"
  = link_to "Log in", login_path, class: "btn btn-info btn-lg"
  = image_tag("bookshelf.png", class: "w-50 mx-auto d-block")

app/views/static_pages/about.html.slim
= provide(:title, "About")
.w-75.mx-auto
  h4.py-4 Welcome to the BookshelfApp wiki!
  section.py-4
    h3 Concept
    ul
      li A combination of bookshelf app and Twitter
      li A test sample after studying the Ruby on Rails tutorial
      li A purpose is to promote fixing the knowledge.
  section.py-4
    h3 Functions
    ul
      li login / logout
      li evaluate books
      li make comments for books
      li follow users
    p If possible, the following functions will be added.
    ul
      li good button for comment written by other users
      li search books

app/views/static_pages/contact.html.slim
= provide(:title, "Contact")
h4.pt-4.text-center This is a Contact page!
= image_tag "contact.jpg", class: "img-fluid w-75 mx-auto d-block py-4"

app/views/static_pages/help.html.slim
= provide(:title, "Help")
h4.pt-4.text-center This is a Help page!
= image_tag "help.jpg", class: "imag-fluid w-75 mx-auto d-block py-4"

app/views/static_pages/home.html.slim
  - if logged_in?
    = render 'home_logged_in'
  - else
    = render 'home_not_logged_in'