config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :update, :edit]
  resources :books, only: [:new, :create, :edit, :update, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :user_id, presence: true
  validates :title, presence: true, length: {maximum: 50}
  validates :content, presence: true, length: {maximum: 800}

  mount_uploader :picture
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def new
    @book = Book.new
  end

  def create
    @book = current_user.books.build(books_params)
    if @book.save
      flash[:success] = "New books added to your bookshelf!"
      redirect_to root_url
    else
      @feed_items = []
      render 'new'
    end
  end

  def edit
    @book = Book.find_by(id: params[:id])
  end

  def update
    @book = Book.find_by(id: params[:id])
    if @book.update_attributes(books_params)
      flash[:success] = "Successfully updated"
      redirect_to root_url
    else
      render 'edit'
    end
  end

  def destroy
    @book.destroy
    flash[:success] = "Book deleted"
    redirect_back(fallback_location: root_url)
  end

  private

    def books_params
      params.require(:book).permit(:title, :content, :picture)
    end

    def correct_user
      @book = current_user.books.find_by(id: params[:id])
      redirect_to root_url if @book.nil?
    end
end

app/views/books/_book.html.slim
li.list-unstyled.border-top.border-secondary
  h4.mt-3.ml-4 = link_to book.title, "https://www.amazon.co.jp/%E6%9C%AC-%E9%80%9A%E8%B2%A9/b/ref=sd_allcat_jb?ie=UTF8&node=465392", class: "text-dark"
  - if book.picture?
    = image_tag(book.picture.url, class: "img-fluid w-50 mx-auto d-block py-4")
  - else
    = image_tag("book-initial.jpg", class: "img-fluid w-50 mx-auto d-block py-4")
  h5.mt-3.ml-4.font-weight-normal = simple_format(book.content)
  p.mt-5.text-right
    span Posted by 
    = link_to book.user.name, user_path(book.user), class: "mr-2"
    span.mr-2 |
    span.mr-2 #{time_ago_in_words(book.created_at)} ago.
    - if current_user?(book.user)
      span.mr-2 |
      span.mr-2 = link_to "Edit", edit_book_path(book)
      span.mr-2 |
      span = link_to "Delete", book, method: :delete, data: {confirm: "You sure?"}

app/views/books/edit.html.slim
= provide(:title, "Edit book")
h1.text-center.my-3 Edit book
.row
  .col-md-6.col-md-offset-3.mx-auto.d-block
    = form_for @book do |f|
      = render 'shared/error_messages', object: f.object
      = f.label :title
      = f.text_field :title, class: "form-control", placeholder: "Book title"
      = f.label :content
      = f.text_area :content, class: "form-control pb-5", placeholder: "Please write your comments in 800 words"
      p Book image ( not necessarily )
      = f.file_field :picture, accept: 'image/jpg, image/gif, image/png', class: "rounded"
      = f.submit "Edit", class: "btn btn-info btn-lg my-3"

app/views/books/new.html.slim
= provide(:title, "New book")
h1.text-center.my-3 New book
.row
  .col-md-6.col-md-offset-3.mx-auto.d-block
    = form_for @book do |f|
      = render 'shared/error_messages', object: f.object
      = f.label :title
      = f.text_field :title, placeholder: "Book title", class: "form-control"
      = f.label :content
      = f.text_area :content, placeholder: "Please write your comments in 800 words", class: "form-control pb-5"
      p Book image ( not necessarily )
      = f.file_field :picture, accept: 'image/jpg, image/gif, image/png', class:"rounded"
      = f.submit "Post", class: "btn btn-info btn-lg my-3"
    = javascript_include_tag "books_new.js"