config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :update, :edit]
  resources :books, only: [:new, :create, :edit, :update, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_footer.html.slim
footer.py-1.bg-dark
  .container.text-center
    ul.nav.justify-content-center.mb-3
      li.navbar-item = link_to "Home", root_path, class: "nav-link text-light"
      li.navbar-item = link_to "About", about_path, class: "nav-link text-light"
      li.navbar-item = link_to "Help", help_path, class: "nav-link text-light"
      li.navbar-item = link_to "Contact", contact_path, class: "nav-link text-light"
    p
      small.text-light
        | Copyright &copy; Masashi Fukuzawa, All Rights Reserved.

app/views/layouts/_header.html.slim
header.py-2
  nav.navbar.navbar-dark.bg-dark.navbar-expand-md
    .container
      = link_to "Bookshelf App", root_path, class: "navbar-brand" 
      button.navbar-toggler type="button" data-toggle="collapse" data-target="#navbar-content" 
        span.navbar-toggler-icon
      .collapse.navbar-collapse#navbar-content
        ul.navbar-nav.ml-5.mr-auto
          li.navbar-item.mr-4 = link_to "Home", root_path, class: "nav-link"
          li.navbar-item.mr-4 = link_to "About", about_path, class: "nav-link"
          - if logged_in?
            li.navbar-item = link_to "Users", users_path, class: "nav-link"
        - if logged_in?
          ul.navbar-nav.text-light.ml-5
            li.navbar-item.dropdown
              = link_to "Account", '#', 'data-toggle': 'dropdown', class: "nav-link dropdown-toggle"
              .dropdown-menu
                = link_to "Profile", user_path(current_user), class: "dropdown-item"
                = link_to "Setting", edit_user_path(current_user), class: "dropdown-item"
                = link_to "Log out", logout_path, method: :delete, class: "dropdown-item"
        - else
          ul.navbar-nav.text-light.ml-5
            li.navbar-item.mr-4 = link_to "Sign up", signup_path, class: "nav-link"
            li.navbar-item = link_to "Log in", login_path, class: "nav-link"

app/views/layouts/application.html.slim
doctype html
html lang="ja"
  head
    title = full_title(yield(:title))
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = favicon_link_tag 'favicon.ico'

  body
    = render 'layouts/header'
    main
      - flash.each do |message_type, message|
        div class="alert alert-#{message_type} text-center" = message
      = yield
      = render 'layouts/footer'
      .p-5.bg-light
        = debug(params) if Rails.env.development?